import assert from 'node:assert/strict';
import { canonicalStreet, resolveOfficialStreet } from '../src/utils/streetMatching.ts';
import { computeBidirectionalBenchmarks } from '../src/utils/bidirectionalBenchmark.ts';
import { getCachedCoords, geocodeCache, cleanQuery } from '../geocodeService.ts';
assert.equal(canonicalStreet('Av. Dr. Fábio da Luz, 25'),canonicalStreet('Avenida Doutor Fabio Luz'));
assert.equal(resolveOfficialStreet('Rua Noronha Torrezao',['Rua Noronha Torrezão','Rua Noronha de Souza']),'Rua Noronha Torrezão');
assert.equal(resolveOfficialStreet('Rua Bento Goncalvez',['Rua Bento Gonçalves']),'Rua Bento Gonçalves');
assert.equal(resolveOfficialStreet('Rua Jose Silv',['Rua Jose Silva','Rua Jose Silveira']),null);
assert.notEqual(canonicalStreet('Rua Santa Rosa'),canonicalStreet('Rua Rosa'));
assert.notEqual(canonicalStreet('Rua 1'),canonicalStreet('Rua 2'));
const txs=[90,100,110].map((sizeSqm,i)=>({id:String(i),street:'Rua Bento Gonçalves',number:'411',sizeSqm,unitValueSqm:4000,propertyType:'Casa',neighborhood:'Benfica',city:'Juiz de Fora',state:'MG'}));
const a=computeBidirectionalBenchmarks(txs as any,'Rua Bento Goncalvez', '411',100,'similar',0.5,'Casa');
const b=computeBidirectionalBenchmarks(txs as any,'Rua Bento Gonçalves', '411',100,'similar',0.5,'Casa');
assert.deepEqual(a,b);
const key=cleanQuery('Rua Teste Unico, 10');
geocodeCache[key]={lat:-22.9,lng:-43.1,displayName:'Rua Teste Unico, 10, Niterói',matchedStreet:'Rua Teste Unico',matchedCity:'Niterói',matchedNumber:'10',precision:'rooftop'};
assert.equal(getCachedCoords('Rua Teste Unico, 10','','Niterói','RJ')?.precision,'rooftop');
geocodeCache[cleanQuery('Rua Teste Unico, 20')]=geocodeCache[key];
assert.equal(getCachedCoords('Rua Teste Unico, 20','','Niterói','RJ'),null);
assert.equal(getCachedCoords('Rua Teste Unico, 10','','Rio de Janeiro','RJ'),null);
console.log('PASS: shared street matching, ambiguity, typology benchmark and number/city cache isolation');
